### ISSUE TITLE
feature/suggestion - icon, alternate way of navigating

### ISSUE THREAD

**Issue by atomGit** [jokokko/breadcrumbus#2]
if there has to be an icon to use the extension due to limitations of WebExt API, it would be nice to have an option to always show it in the address bar perhaps, not just when it loads the URL

however, what i find much easier is to use the scroll wheel to segment the URL - [Scroll Up Folder](https://addons.mozilla.org/en-US/firefox/addon/scroll-up-folder/) works this way, but its legacy

another method is to segment the URL in the address bar so its parts can be clicked (if the WebExt API allows)

either way, i imagine it would be less code since you wouldn't need an icon or the panel that displays the segments

thanks for segmenting parameters though! a lot of these type add-ons fail to do this

**Comment by jokokko** [comment]
Thanks for the feedback.

The icon should always show up in the address bar (given URI does not start with about:), given it's not disabled through settings. If that's not the case, then I have to investigate.

As for modifying the address bar, that is unfortunately not possible with the new extension model. I understand the wish - I actually created myself this extension just because the legacy breadcrumb extensions were not going to work :(

**Comment by atomGit** [comment]
> The icon should always show up in the address bar ...

it does - sorry about that - it just wasn't there right after i installed it - i might have had an about: page focused, don't recall, but i'm pretty sure it didn't show up on any other page until i first clicked the tool-bar icon - that's when i noticed it appear in the address bar (not sure if i just clicked the icon, or i had to load a URL segment, but pretty sure the latter before it showed up in the address bar)

hopefully the API will be extended in the future
